local ll = require('src.linked_list')

describe('linked list', function()
  it('should create an empty linked list', function()
    local l = ll.LinkedList:new()
    -- l:printList()
  end)

  it('should create an empty linked list and add one Node at the end', function()
    local l = ll.LinkedList:new()
    l:append(1)
    -- l:printList()
  end)

  it('should create an empty linked list and add 3 Node at the end', function()
    local l = ll.LinkedList:new()
    l:append(1)
    l:append(2)
    l:append(3)
    -- l:printList()
  end)

  it('should create an empty linked list and add one Node at the end and remove it', function()
    local l = ll.LinkedList:new()
    l:append(1)
    -- l:printList()
    l:remove(1)
    -- l:printList()
  end)

  it('should create an empty linked list and add 3 Node at the end and remove middle', function()
    local l = ll.LinkedList:new()
    l:append(1)
    l:append(2)
    l:append(3)
    -- l:printList()
    l:remove(2)
    -- l:printList()
  end)

  it('should create an empty linked list and add 3 Node at the end and remove first', function()
    local l = ll.LinkedList:new()
    l:append(1)
    l:append(2)
    l:append(3)
    -- l:printList()
    l:remove(1)
    -- l:printList()
  end)
end)
